### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [AICP/device_oneplus_sm8250-common#2]
FAILED: out/target/product/kebab/obj/FAKE/sepolicy_neverallows_intermediates/se
policy_neverallows
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -
M -c 		30 -o out/target/product/kebab/obj/FAKE/sepolicy_neverallows_in
termediates/sepolicy_neverallows.tmp out/target/product/kebab/obj/FAKE/sepolicy
_neverallows_intermediates/policy.conf ) && (out/host/linux-x86/bin/sepolicy-an
alyze out/target/product/kebab/obj/FAKE/sepolicy_neverallows_intermediates/sepo
licy_neverallows.tmp neverallow -w -f out/target/product/kebab/obj/FAKE/sepolic
y_neverallows_intermediates/policy_2.conf || 	  ( echo \"\" 1>&2; 	    ech
o \"sepolicy-analyze failed. This is most likely due to the use\" 1>&2; 	 
   echo \"of an expanded attribute in a neverallow assertion. Please fix\" 1>&2
; 	    echo \"the policy.\" 1>&2; 	    exit 1 ) ) && (touch out/target/pro
duct/kebab/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp
 ) && (mv out/target/product/kebab/obj/FAKE/sepolicy_neverallows_intermediates/
sepolicy_neverallows.tmp out/target/product/kebab/obj/FAKE/sepolicy_neverallows
_intermediates/sepolicy_neverallows )"
libsepol.report_failure: neverallow on line 4 of system/sepolicy/private/coredo

**Comment by LMAO-armv8** [comment]
Sir plz help if u have fixed this issue

**Comment by LMAO-armv8** [comment]
FAILED: out/target/product/m31/obj/FAKE/sepolicy_neverallows_intermediates/sepol
icy_neverallows                                                                 
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M
 -c             30 -o out/target/product/m31/obj/FAKE/sepolicy_neverallows_inter
mediates/sepolicy_neverallows.tmp out/target/product/m31/obj/FAKE/sepolicy_never
allows_intermediates/policy.conf ) && (out/host/linux-x86/bin/sepolicy-analyze o
ut/target/product/m31/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_never
allows.tmp neverallow -w -f out/target/product/m31/obj/FAKE/sepolicy_neverallows
_intermediates/policy_2.conf ||           ( echo \"\" 1>&2;         echo \"sepol
icy-analyze failed. This is most likely due to the use\" 1>&2;      echo \"of an
 expanded attribute in a neverallow assertion. Please fix\" 1>&2;           echo
 \"the policy.\" 1>&2;      exit 1 ) ) && (touch out/target/product/m31/obj/FAKE
/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp ) && (mv out/target
/product/m31/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tm
p out/target/product/m31/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_ne
verallows )"                                                                    
device/lineage/sepolicy/common/vendor/hal_lineage_livedisplay_sysfs.te:2:ERROR '
Duplicate declaration of type' at token ';' on line 60276:                      
type hal_lineage_livedisplay_sysfs, domain;                                     
#line 1 "device/lineage/sepolicy/common/vendor/hal_lineage_livedisplay_sysfs.te"
checkpolicy:  error(s) encountered while parsing configuration

**Comment by eyosen** [comment]
You have two issues:
First you are hitting a neverallow at Line 4 
ibsepol.report_failure: neverallow on line 4 of system/sepolicy/private/coredo
Secondly, the message tells you what the error is:
"Duplicate declaration of type' at token ';' on line 60276:"
You have declared that type twice
Please read carefully
